import json,pathlib
p=pathlib.Path('data/workbook.json');d=json.loads(p.read_text())
rows=[
('BOI Por.8/2568','BOI 第 Por.8/2568 号公告','ประกาศ BOI ป.8/2568','Position, placement and extension criteria. Government-hosted unofficial English translation; confirm the Thai original.','职位、人员及延期标准。政府发布的非官方英译；请核对泰文原文。','เกณฑ์ตำแหน่ง บรรจุ และขยายเวลา ฉบับแปลอังกฤษไม่เป็นทางการ โปรดตรวจสอบต้นฉบับไทย','https://www.boi.go.th/upload/content/por8_2568EN.pdf','BOI'),
('Department of Employment','泰国就业厅','กรมการจัดหางาน','Work permit services; confirm the applicable BOI channel.','工作许可服务；请确认适用的 BOI 渠道。','บริการใบอนุญาตทำงาน โปรดยืนยันช่องทาง BOI ที่เกี่ยวข้อง','https://eworkpermit.doe.go.th/Home','DOE'),
('Immigration re-entry handbook','移民局再入境手册','คู่มือการขอกลับเข้าประเทศ','Re-entry procedure. Check current forms and office requirements.','再入境程序。请确认最新表格及主管机关要求。','ขั้นตอนกลับเข้าประเทศ โปรดตรวจสอบแบบฟอร์มและข้อกำหนดล่าสุด','https://www.immigration.go.th/citizen_manual/guid_en5.pdf','Immigration Bureau'),
('Chengdu B / IB visa FAQ','成都领馆 B / IB 签证问答','คำถามวีซ่า B / IB สถานกงสุลเฉิงตู','China-based consular guidance; requirements depend on jurisdiction and purpose.','驻华领事指导；要求取决于领区和目的。','คำแนะนำกงสุลในจีน ข้อกำหนดขึ้นอยู่กับเขตอำนาจและวัตถุประสงค์','https://chengdu.thaiembassy.org/th/content/business-or-employment-visa-non-immigrant-b-ib?menu=68db8e1aae8d891b84392313&page=68db98b312577f346474c7c4','Royal Thai Consulate-General, Chengdu')]
for i,r in enumerate(rows):d['resources'].append({'id':'research-'+str(i),'name':dict(zip(['en','zh','th'],r[:3])),'purpose':dict(zip(['en','zh','th'],r[3:6])),'url':r[6],'authority':r[7],'provenance':'research','verified':True})
d['notices']=[{'name':{'en':'2026 Single Window updates','zh':'2026 年 Single Window 更新','th':'ข้อมูลปรับปรุง Single Window ปี 2026'},'text':{'en':'Review current TIESC Digital Work Permit steps and extension income-evidence notices before submission. Procedures vary by application.','zh':'提交前请查看 TIESC 数字工作许可流程及延期收入证明通知。流程因申请而异。','th':'ตรวจสอบขั้นตอนใบอนุญาตทำงานดิจิทัล TIESC และประกาศหลักฐานรายได้ก่อนยื่น ขั้นตอนต่างกันตามคำขอ'},'url':'https://swe-expert.boi.go.th/main.php'}]
p.write_text(json.dumps(d,ensure_ascii=False,indent=2))
