"""Extract the inspected, non-personal workbook template. Never export employee rows."""
import json,pathlib,openpyxl
root=pathlib.Path(__file__).resolve().parent.parent
w=openpyxl.load_workbook(next(root.glob('*.xlsx')))
keys={1:['no','name','englishName','passport','nationality','department','position','positionId','location','startDate','positionApprovalDate','personnelApprovalDate','visaExpiry','stayExpiry','wpExpiry','reentry','dependants','passportExpiry','owner','status','remarks'],2:['category','name','employeeA','employeeB','employeeC','remarks'],3:['no','title','recommended','department','responsibilities','requirements','status','remarks'],4:['title','category','recommended','plannedStart','plannedEnd','stage','owner','remarks'],5:['employeeId','category','estimated','actual','paymentDate','vendor','status','remarks'],6:['employeeId','item','expiry','days','alert','owner','action','remarks'],7:['employeeId','positionId','positionStatus','lastDate','wpStatus','stayStatus','departure','replacementId','application','owner','remarks'],8:['name','url','purpose']}
names={1:'employees',2:'documents',3:'positions',4:'batches',5:'budget',6:'renewals',7:'changes',8:'resources'}
def tri(v):
 if v is None:return ''
 if not isinstance(v,str):return v
 a=v.split('\n')
 return dict(zip(['zh','en','th'],a)) if len(a)==3 else v
out={'schema':{},'source':'Rev01 workbook template','reviewed':'2026-09-15'}
for i,ks in keys.items():
 s=w.worksheets[i];name=names[i];out['schema'][name]=dict(zip(ks,[tri(c.value) for c in s[1]]))
 if i in [2,3,4,5,8]:
  out[name]=[dict(id=name+'-'+str(r[0].row-1),**{k:tri(c.value) for k,c in zip(ks,r) if k not in ['employeeA','employeeB','employeeC']}) for r in list(s)[1:]]
for p in out['positions']:p.update(approved=None,approvalDate='',owner='')
for b in out['budget']:b.update(quantity=None,unitCost=None,description='')
for b in out['batches']:b.update(actualStart='',actualEnd='',progress=0)
for r in out['resources']:r.update(authority='BOI',provenance='workbook',verified=True)
(root/'data').mkdir(exist_ok=True)
(root/'data/workbook.json').write_text(json.dumps(out,ensure_ascii=False,indent=2))
report=['# Workbook analysis and design decisions','', 'All nine sheets, meaningful cells, 1,006 formulas, two dropdown validations, and all conditional-format rules were inspected. The 1,000 renewal formulas normalize to two repeated patterns. Raw cell inspection is kept locally and excluded from deployment.','', '| Worksheet | Module | Content |','|---|---|---|']
for i,s in enumerate(w):report.append('|'+s.title+'|'+(['Dashboard']+[names[j] for j in range(1,9)])[i]+'|'+str(s.max_row)+' rows × '+str(s.max_column)+' columns|')
report += ['', '## Relationships and rules', '- Employee is the parent record. Employee documents use employee ID + document ID. Renewal rows derive from four master expiry fields; only actions and notes are stored separately. Positions and replacement employees are referenced by ID.', '- Dashboard: COUNTA on employee name; status COUNTIF for Processing and WP issued; three COUNTIFS for dates from today through today + 30 inclusive. Web counts actual named records, excluding the 30 empty template slots.', '- Renewal: expiry minus TODAY(); expired < 0; red 0–30; yellow 31–60; blue 61–90; normal >90. Master formatting instead uses amber 31–90 and does not mark expired dates. Per the explicit brief, web uses expired/red ≤30, amber 31–60, green >60. These are internal planning alerts, not statutory filing deadlines.', '- Use Asia/Bangkok calendar dates and UTC day arithmetic to avoid timezone/DST errors. Missing dates remain unknown.', '- All 21 Master fields retained. All 16 checklist items retained, including re-entry and dependant visa/stay. Seven employee statuses and four dependant options retained.', '- Eleven recommended positions total 23 plus as-required project/training experts. Recommended numbers are not approved quotas. Approval count, date, owner and assignment links are additions; unknown approval remains null.', '- Four batches retain headcount ranges, owners and original stages. No dates supplied; progress 0 is an editable planning baseline, not a BOI processing estimate.', '- Seven budget categories have no numeric costs. Unknown budget/actual values remain null; never interpreted as free or zero. Payment date and vendor retained. Optional quantity, unit cost and description are additions.', '- Offboarding has headers only. All eleven fields retained. Actions require HR confirmation; changing a workflow does not submit to any authority.', '', '## Information architecture and UI plan', 'Nine connected navigation modules; employee detail consolidates master fields, document checklist, renewal actions and local history. Navy sidebar, warm neutral canvas, teal accents, clear red/amber expiry cues. Responsive cards and horizontally scrollable tables. Central trilingual dictionary plus workbook translations.', '', '## Data architecture', 'Static ES modules + JSON. Repository adapter handles demo localStorage persistence. UI and calculations consume entities through this adapter so a future authenticated API can replace storage. No upload of personal documents. Public build uses explicit asset allowlist.', '', '## Assumptions', 'Workbook is a planning template, not evidence of approved positions or actual employees. Public employees are explicitly synthetic DEMO records. User-generated text is preserved in its entered language; UI and workbook terminology switch centrally. Actual employee data must wait for a secure backend.']
(root/'docs/workbook-analysis.md').write_text('\n'.join(report))
print('Extracted template schemas and all populated planning rows; documented design before application code.')
